### PR TITLE
Update copyright footers from 2017 to 2018

### PR DESCRIPTION
**Pull request by issmirnov**
Noticed a few prominent footers with 2017 copyrights.

### CODE REVIEW

**Comment by boyter** [comment]
One of those ones I should make driven from the back-end so its always up to date. Ill merge this in the morning then fix it so its solved for good.

**Comment by boyter** [comment]
Oh one thing before I can merge this, I just need your conformation that you are fine with your change being licensed under "Apache Public License v2 and GPL v3". This ensures I can continue offering the paid version and then GPL3 when the the 3 year eventually open clause kicks in :)

**Comment by issmirnov** [comment]
Oh yeah totally, it's a 3 line trivial delta :)

**Comment by boyter** [comment]
Just need to cross t's and dot i's to ensure I don't run afoul of licensing issues in the future :)

**Comment by boyter** [comment]
Should mention I changed this again to use the data value in Freemarker so its always set to the current year. Should save the effort of updating again in the future.

**Pull request merged**
